name: Run Selenium TOTO Scraper

on:
  schedule:
    - cron: '0 12 * * *'   # 8:00 PM SGT
    - cron: '0 13 * * *'   # 9:00 PM SGT
    - cron: '0 14 * * *'   # 10:00 PM SGT
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: latest

    - name: Run scraper
      run: python selenium_scraper.py

    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/toto_result.json
        git diff --cached --quiet || git commit -m "Update TOTO results"
        git push
